#https://www.strobe-statement.org

using DataFrames

combined_df = DataFrame(
    "" => [
        "Title and abstract", 
        missing,
        "Introduction", 
        "Background/rationale",
        "Objectives",
        "Methods",
        "Study design",
        "Setting",
        "Participants",
        missing,
        "Variables",
        "Data sources/measurement",
        "Bias",
        "Study size",
        "Quantitative variables",
        "Statistical methods",
        missing,
        missing,
        missing,
        missing,
        "Results",
        "Participants",
        missing,
        missing,
        "Descriptive data",
        missing,
        missing,
        "Outcome data",
        missing,
        missing,
        "Main results",
        missing,
        missing,
        "other analyzes",
        "Discussion",
        "Key results",
        "Limitations",
        "Interpretation",
        "Generalizability",
        "Other information",
        "Funding"
    ],
    "Item No." => [
        1, 
        missing,
        missing,
        2, 
        3, 
        missing,
        4, 
        5, 
        6, 
        missing,
        7, 
        8, 
        9,
        10,
        11,
        12,
        missing,
        missing,
        missing,
        missing,
        missing,
        13,
        missing,
        missing,
        14,
        missing,
        missing,
        15,
        missing,
        missing,
        16,
        missing,
        missing,
        17,
        missing,
        18,
        19,
        20,
        21,
        missing,
        22
    ],
    "Recommendation" => [
        "(a) Indicate the study's design with a commonly used term in the title or the abstract", 
        "(b) Provide in the abstract an informative and balanced summary of what was done and what was found",
        missing,
        "Explain the scientific background and rationale for the investigation being reported",
        "State specific objectives, including any prespecified hypotheses",
        missing,
        "Present key elements of study design early in the paper",
        "Describe the setting, locations, and relevant dates, including periods of recruitment, exposure, follow-up, and data collection",
        "(a) Cohort study—Give the eligibility criteria, and the sources and methods of selection of participants. Describe methods of follow-up\n Case-control study—Give the eligibility criteria, and the sources and methods of case ascertainment and control selection. Give the rationale for the choice of cases and controls\n Cross-sectional study—Give the eligibility criteria, and the sources and methods of selection of participants",
        "(b) Cohort study—For matched studies, give matching criteria and number of exposed and unexposed\n Case-control study—For matched studies, give matching criteria and the number of controls per case",
        "Clearly define all outcomes, exposures, predictors, potential confounders, and effect modifiers. Give diagnostic criteria, if applicable",
        "For each variable of interest, give sources of data and details of methods of assessment (measurement). Describe comparability of assessment methods if there is more than one group",
        "Describe any efforts to address potential sources of bias",
        "Explain how the study size was arrived at",
        "Explain how quantitative variables were handled in the analyses. If applicable, describe which groupings were chosen and why",
        "(a) Describe all statistical methods, including those used to control for confounding",
        "(b) Describe any methods used to examine subgroups and interactions",
        "(c) Explain how missing data were addressed",
        "(d) Cohort study—If applicable, explain how loss to follow-up was addressed\n Case-control study—If applicable, explain how matching of cases and controls was addressed\n Cross-sectional study—If applicable, describe analytical methods taking account of sampling strategy",
        "(e) Describe any sensitivity analyses",
        missing,
        "(a) Report numbers of individuals at each stage of study—eg numbers potentially eligible, examined for eligibility, confirmed eligible, included in the study, completing follow-up, and analysed",
        "(b) Give reasons for non-participation at each stage",
        "(c) Consider use of a flow diagram",
        "(a) Give characteristics of study participants (eg demographic, clinical, social) and information on exposures and potential confounders",
        "(b) Indicate number of participants with missing data for each variable of interest",
        "(c) Cohort study—Summarise follow-up time (eg, average and total amount)",
        "Cohort study—Report numbers of outcome events or summary measures over time",
        "Case-control study—Report numbers in each exposure category, or summary measures of exposure",
        "Cross-sectional study—Report numbers of outcome events or summary measures",
        "(a) Give unadjusted estimates and, if applicable, confounder-adjusted estimates and their precision (eg, 95% confidence interval). Make clear which confounders were adjusted for and why they were included",
        "(b) Report category boundaries when continuous variables were categorized",
        "(c) If relevant, consider translating estimates of relative risk into absolute risk for a meaningful time period",
        "Report other analyses done—eg analyses of subgroups and interactions, and sensitivity analyses",
        missing,
        "Summarise key results with reference to study objectives",
        "Discuss limitations of the study, taking into account sources of potential bias or imprecision. Discuss both direction and magnitude of any potential bias",
        "Give a cautious overall interpretation of results considering objectives, limitations, multiplicity of analyses, results from similar studies, and other relevant evidence",
        "Discuss the generalizability (external validity) of the study results",
        missing,
        "Give the source of funding and the role of the funders for the present study and, if applicable, for the original study on which the present article is based"
    ],
    "Page No." => [
        missing, 
        missing, 
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing
    ],
    "Relevant text from manuscript" => [
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing,
        missing
    ]
)

function combined(
    save_location::String = pwd(),
    filename::String = "combined",
    filetype::String = "csv",
    sheetname::String = "combined",
)
    if filetype == "csv"
        CSV.write("$save_location/$filename.csv", combined_df)
        println("$filename.csv to $save_location")
    elseif filetype == "xlsx"
        XLSX.writetable(xlsx_filename, DataFrame(combined_df), sheetname = sheetname)
        println("$filename.xlsx to $save_location")
    else
        println("Unsupported file type: $filetype")
    end
end

function combined_csv(save_location::String = pwd(), filename::String = "combined")
    CSV.write("$save_location/$filename.csv", combined_df)
end

function combined_xlsx(save_location::String = pwd(), filename::String = "combined")
    XLSX.writetable("$save_location/$filename.xlsx", combined_df)
end